name: Deploy ASP.NET Core API to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]   # Deploy whenever main branch updates

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # match your project SDK

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Zip artifact
        run: |
          cd publish
          zip -r ../app.zip .
          cd ..

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "YourElasticBeanstalkAppName"
          environment_name: "YourEnvironmentName"
          version_label: v-${{ github.run_number }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: "app.zip"