name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: ["main"]   # Adjust branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'   # Or whatever version you target

      # Install AWS EB CLI
      - name: Install AWS Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade --user
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Publish from subfolder
      - name: Publish .NET project
        run: dotnet publish ./PaymentProcessorSimulatorAPI/PaymentProcessorSimulatorAPI/PaymentProcessorSimulatorAPI.csproj -c Release -o ./publish

      # Zip deployment package
      - name: Zip deployment package
        run: |
          cd publish
          zip -r ../app.zip .
          cd ..

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
        run: |
          eb init $EB_APPLICATION_NAME --region $AWS_REGION --platform "dotnet-core"
          eb use $EB_ENVIRONMENT_NAME
          eb deploy
